# Generated by Django 2.0.6 on 2020-03-18 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_users_performance'),
        ('trainapp', '0002_train_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='dept_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.Dept'),
            preserve_default=False,
        ),
    ]
