# Generated by Django 2.0.6 on 2020-03-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='salary',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
