# Generated by Django 2.0.6 on 2020-03-17 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0002_title_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='salary',
        ),
    ]
