# Generated by Django 2.0.6 on 2020-03-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('pic', models.FileField(upload_to='pics')),
            ],
            options={
                'db_table': 'pic',
            },
        ),
    ]
