# Generated by Django 2.0.6 on 2020-03-16 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dept_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.Dept'),
            preserve_default=False,
        ),
    ]
