# Generated by Django 2.0.6 on 2020-03-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_users_dept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='salary',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
