# Generated by Django 2.0.6 on 2020-03-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_dept_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='performance',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
